authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('update/', authapp.update, name='update'),
    path('verify/<email>/<key>', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
import authapp.views as authapp
import adminapp.views as adminapp
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('my/admin/',include('adminapp.urls', namespace='my_admin')),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('catalog/', mainapp.products, name='products'),
    path('contacts/', mainapp.contact, name='contact'),
    re_path(r'^category/(?P<pk>\d+)/products/$', mainapp.category_products, name='category_products'),
    re_path(r'^category/(?P<pk>\d+)/products/(?P<page>\d+)/$', mainapp.category_products, name='category_products_pagination'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product_page, name='product_page'),
]

mainapp/models.py
from django.db import models

# SomeModel.objects.filter(id=id).delete() - для себя, удаление элемента модели
class ProductCategory(models.Model):
    name = models.CharField('имя категории', max_length=64)
    description = models.TextField('описание категории', blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name}"

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, verbose_name='категория продукта', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=64, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, ProductCategory
import random
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator


def get_basket(request):
    return request.user.is_authenticated and request.user.basket.all() or []


def get_menu():
    return ProductCategory.objects.filter(is_active=True)


def index(request):
    context = {
        'page_title': 'главная',
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/index.html', context)


def products(request):
    hot_product_pk = random.choice(Product.objects.filter(is_active=True).values_list('pk', flat=True))
    hot_product = Product.objects.get(pk=hot_product_pk)

    same_products = hot_product.category.product_set.filter(is_active=True).exclude(pk=hot_product.pk)

    context = {
        'page_title': 'каталог',
        'categories': get_menu(),
        'basket': get_basket(request),
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/products.html', context)


def category_products(request, pk, page=1):
    if pk == '0':
        category = {'pk': 0, 'name': 'все'}
        products = Product.objects.filter(is_active=True)
    else:
        category = get_object_or_404(ProductCategory, pk=pk)
        products = category.product_set.filter(is_active=True)

    products_paginator = Paginator(products, 3)
    try:
        products = products_paginator.page(page)
    except PageNotAnInteger:
        products = products_paginator.page(1)
    except EmptyPage:
        products = products_paginator.page(products_paginator.num_pages)


    context = {
        'page_title': 'каталог',
        'categories': get_menu(),
        'products': products,
        'category': category,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/category_products.html', context)


def product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'page_title': 'каталог',
        'categories': get_menu(),
        'category': product.category,
        'basket': get_basket(request),
        'product': product,
    }
    return render(request, 'mainapp/product.html', context)


def contact(request):
    locations = [
        {
            'city': 'Москва',
            'phone': '+7-495-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
        {
            'city': 'Санкт-Петербург',
            'phone': '+7-812-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах КАД',
        },
        {
            'city': 'Владивосток',
            'phone': '+7-111-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах города',
        },
    ]
    context = {
        'page_title': 'контакты',
        'locations': locations,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/contact.html', context)

mainapp/templates/mainapp/includes/inc__category_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li>
            <a href="{% url 'main:category_products' 0 %}"
               class="{% if request.resolver_match.kwargs.pk == '0' %}active{% endif %}">
                все
            </a>
        </li>

        {% for category in categories %}
            <li>
                <a href="{% url 'main:category_products' category.pk %}"
                   class="{% if request.resolver_match.kwargs.pk|add:0 == category.pk %}active{% endif %}">
                    {{ category.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>

mainapp/templates/mainapp/includes/inc__main_menu.html
<div class="header clearfix">
    <a href="{% url 'main:index' %}" class="logo"></a>
    <ul class="menu">
        <li>
            <a href="{% url 'main:index' %}" class="active">
                домой
            </a>
        </li>
        <li>
            <a href="{% url 'main:products' %}">
                продукты
            </a>
        </li>
        <li>
            <a href="{% url 'main:contact' %}">
                контакты
            </a>
        </li>
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'auth:update' %}">
                    {{ user.first_name|default:'пользователь'|title }}
                </a>
            </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">
                    выход
                </a>
            {% else %}
                <a href="{% url 'auth:login' %}">
                    вход
                </a>
            {% endif %}
            {% if user.is_superuser %}
            <li>
                <a href="{% url 'my_admin:index' %}">
                    админка
                </a>
            </li>
        {% endif %}
        </li>

    </ul>
    <a href="#" class="search"></a>
    <a href="{% url 'basket:index' %}" class="basket">
    <span>
        {% if basket %}
            {{ basket.0.total_cost|floatformat:0 }} руб ({{ basket.0.total_quantity }} шт)
        {% endif %}
    </span>
    </a>
</div>