authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('update/', authapp.update, name='update'),
    path('verify/<email>/<key>', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
import authapp.views as authapp
import adminapp.views as adminapp
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('my/admin/',include('adminapp.urls', namespace='my_admin')),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('catalog/', mainapp.products, name='products'),
    path('contacts/', mainapp.contact, name='contact'),
    re_path(r'^category/(?P<pk>\d+)/products/$', mainapp.category_products, name='category_products'),
    re_path(r'^category/(?P<pk>\d+)/products/(?P<page>\d+)/$', mainapp.category_products, name='category_products_pagination'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product_page, name='product_page'),
]

authapp/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
import pytz
from django.conf import settings
from datetime import datetime, timedelta


class ShopUser(AbstractUser):
    age = models.PositiveSmallIntegerField(verbose_name='возраст', null=True)
    avatar = models.ImageField(upload_to='users_avatars', blank=True)

    activation_key = models.CharField(max_length=128, verbose_name='ключ активации', blank=True, null=True)
    activation_key_expires = models.DateTimeField(blank=True, null=True)

    def is_activate_key_expired(self):
        if datetime.now(pytz.timezone(settings.TIME_ZONE)) > self.activate_key_expired + timedelta(hours=48):
            return True
        return False

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
import django.forms as forms
from authapp.models import ShopUser
import pytz
from django.conf import settings
from datetime import datetime
import hashlib


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password1', 'password2', 'email',
        'first_name', 'last_name', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Пользователь слишком молод!")
        return data

    def save(self, *args, **kwargs):
        user = super().save(*args, **kwargs)
        user.is_active = False

        user.activate_key = hashlib.sha1(user.email.encode('utf8')).hexdigest()
        user.activate_key_expired = datetime.now(pytz.timezone(settings.TIME_ZONE))
        user.save()

        return user



class ShopUserUpdateForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password', 'email',
        'first_name', 'last_name', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'password':
                field.widget = forms.HiddenInput()
            else:
                field.widget.attrs['class'] = f'form-control {field_name}'
                field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Пользователь слишком молод!")
        return data

authapp/views.py
from django.contrib import auth
from django.shortcuts import render
from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserUpdateForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.mail import send_mail
from django.conf import settings
from authapp.models import ShopUser


def login(request):
    next = request.GET.get('next', '')
    if request.method == 'POST':
        form = ShopUserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                if 'next' in request.POST.keys():
                    return HttpResponseRedirect(request.POST['next'])
                else:
                    return HttpResponseRedirect(reverse('main:index'))
    else:
        form = ShopUserLoginForm()
    context = {
        'title': 'вход в систему',
        'form': form,
        'next': next,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    if request.method == 'POST':
        form = ShopUserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:index'))

    else:
        form = ShopUserRegisterForm()
    context = {
        'title': 'регистрация пользователя',
        'form': form,
    }
    return render(request, 'authapp/register.html', context)


def update(request):
    if request.method == 'POST':
        form = ShopUserUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:update'))

    else:
        form = ShopUserUpdateForm(instance=request.user)
    context = {
        'title': 'Данные пользователя',
        'form': form,
    }
    return render(request, 'authapp/update.html', context)


def verify(request, email, key):
    pass


def send_verify_mail(user):
    verify_link = reverse('authapp:verify', args=[user.email, user.activate_key])
    full_link = f'{settings.BASE_URL}{verify_link}'

    message = f' Your activation url: \n{full_link}'

    send_mail(
        'Account activation',
        message,
        settings.EMAIL_HOST_USER,
        [user.email],
        fail_silently=False
    )
 ###

authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {{ title|capfirst }}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
<div class="container">
    <div class="login">
        {% block container %}
        {% endblock %}
    </div>
</div>
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block container %}
    <div class="h2 text-center head">
        Вход в систему
    </div>
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>
    <a href="{% url 'auth:register' %}"
       class="btn btn-round form-control">
        зарегистрироваться
    </a>

{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block container %}
    <div class="h2 text-center head">
        Регистрация пользователя
    </div>
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>

{% endblock %}

authapp/templates/authapp/update.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block container %}
    <div class="h2 text-center head">
        Данные пользователя
    </div>
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <a class="btn btn-default" href="{% url 'main:index' %}">На главную</a>

{% endblock %}