authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('update/', authapp.update, name='update'),
    path('verify/<email>/<key>', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('add/product/<int:pk>/', basketapp.add_product, name='add_product'),
    path('delete/product/<int:pk>/', basketapp.delete_product, name='delete_product'),
    path('', basketapp.index, name='index'),
    path('change/<int:pk>/quantity/<int:quantity>/', basketapp.change),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp
import authapp.views as authapp
import adminapp.views as adminapp
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('my/admin/',include('adminapp.urls', namespace='my_admin')),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, re_path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('catalog/', mainapp.products, name='products'),
    path('contacts/', mainapp.contact, name='contact'),
    re_path(r'^category/(?P<pk>\d+)/products/$', mainapp.category_products, name='category_products'),
    re_path(r'^category/(?P<pk>\d+)/products/(?P<page>\d+)/$', mainapp.category_products, name='category_products_pagination'),
    re_path(r'^product/(?P<pk>\d+)/$', mainapp.product_page, name='product_page'),
]

mainapp/models.py
from django.db import models

# SomeModel.objects.filter(id=id).delete() - для себя, удаление элемента модели
class ProductCategory(models.Model):
    name = models.CharField('имя категории', max_length=64)
    description = models.TextField('описание категории', blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name}"

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, verbose_name='категория продукта', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=64, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name})"

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, ProductCategory
import random
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator


def get_basket(request):
    return request.user.is_authenticated and request.user.basket.all() or []


def get_menu():
    return ProductCategory.objects.filter(is_active=True)


def index(request):
    context = {
        'page_title': 'главная',
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/index.html', context)


def products(request):
    hot_product_pk = random.choice(Product.objects.filter(is_active=True).values_list('pk', flat=True))
    hot_product = Product.objects.get(pk=hot_product_pk)

    same_products = hot_product.category.product_set.filter(is_active=True).exclude(pk=hot_product.pk)

    context = {
        'page_title': 'каталог',
        'categories': get_menu(),
        'basket': get_basket(request),
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/products.html', context)


def category_products(request, pk, page=1):
    if pk == '0':
        category = {'pk': 0, 'name': 'все'}
        products = Product.objects.filter(is_active=True)
    else:
        category = get_object_or_404(ProductCategory, pk=pk)
        products = category.product_set.filter(is_active=True)

    products_paginator = Paginator(products, 3)
    try:
        products = products_paginator.page(page)
    except PageNotAnInteger:
        products = products_paginator.page(1)
    except EmptyPage:
        products = products_paginator.page(products_paginator.num_pages)


    context = {
        'page_title': 'каталог',
        'categories': get_menu(),
        'products': products,
        'category': category,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/category_products.html', context)


def product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'page_title': 'каталог',
        'categories': get_menu(),
        'category': product.category,
        'basket': get_basket(request),
        'product': product,
    }
    return render(request, 'mainapp/product.html', context)


def contact(request):
    locations = [
        {
            'city': 'Москва',
            'phone': '+7-495-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах МКАД',
        },
        {
            'city': 'Санкт-Петербург',
            'phone': '+7-812-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах КАД',
        },
        {
            'city': 'Владивосток',
            'phone': '+7-111-888-8888',
            'email': 'info@geekshop.ru',
            'address': 'В пределах города',
        },
    ]
    context = {
        'page_title': 'контакты',
        'locations': locations,
        'basket': get_basket(request),
    }
    return render(request, 'mainapp/contact.html', context)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ page_title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="container">
    {% block container %}
        <h1>Stub</h1>
    {% endblock %}
    <div class="clr"></div>
</div>

{% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/category_products.html
{% extends 'mainapp/base.html' %}

{% block container %}
    <div class="hero-white">
        {% include 'mainapp/includes/inc__main_menu.html' %}
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc__category_menu.html' %}

        <div class="related">
            <div class="title clearfix">
                <h2>Продукты в категории {{ category.name|title }}</h2>
                <div class="paginator">
                    {% if products.has_previous %}
                        <a href="{% url 'main:category_products_pagination' category.pk products.previous_page_number %}">
                            <
                        </a>
                    {% endif %}
                    <span class="current">страница {{ products.number }} из {{ products.paginator.num_pages }}</span>
                    {% if products.has_next %}
                        <a href="{% url 'main:category_products_pagination' category.pk products.next_page_number %}">
                            >
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="related-products clearfix">
                {% for product in products %}
                    <div class="block">
                        <a href="{% url 'mainapp:product_page' product.pk %}">
                            <img src="/media/{{ product.image }}" alt="">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.short_desc }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}


{% block container %}
    <div class="hero">
        {% include 'mainapp/includes/inc__main_menu.html' %}
        <h1>наши контакты</h1>
    </div>

    <div class="location">
        {% if locations %}
            {% for item in locations %}
                <div class="location-1">
                    <i class="fa fa-map-marker fa-5x"></i>
                    <h4>{{ item.city }}</h4>
                    <div class="contacts">
                        <h5>Телефон</h5>
                        <p>{{ item.phone }}</p>
                    </div>
                    <div class="contacts">
                        <h5>Email</h5>
                        <p>{{ item.email }}</p>
                    </div>
                    <div class="contacts">
                        <h5>Адрес</h5>
                        <p>{{ item.address }}</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h3>Данные загружаются</h3>
        {% endif %}
    </div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{#{% block title %}#}
{#    {{ block.super }} / main#}
{#{% endblock %}#}

{% block container %}
    <div class="slider">
        {% include 'mainapp/includes/inc__main_menu.html' %}
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>

    <div class="featured">
        <div class="featured-menu">
            <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            <div class="block">
                <a href="#"><img src="{% static '/img/product-1.jpg' %}" alt="">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="img">
                        <h4>Отличный стул</h4>
                        <p>Расположитесь комфортно. </p>
                    </div>
                </a>
            </div>
            <div class="block">
                <a href="#"><img src="{% static 'img/product-2.jpg' %}" alt="">
                    <div class="text">
                        <img src="{% static 'img/icon-hover.png' %}" alt="">
                        <h4>Стул повышенного качества</h4>
                        <p>Не оторваться. </p>
                    </div>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block container %}
    <div class="hero-white">
        {% include 'mainapp/includes/inc__main_menu.html' %}
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc__category_menu.html' %}

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="вариант 1">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="вариант 2">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ product.image }}" alt="вариант 3">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <br>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add_product' product.pk %}" class="red-button">
                    заказать
                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ product.description }}
                </div>
            </div>
        </div>

    </div>

{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block container %}
    <div class="hero-white">
        {% include 'mainapp/includes/inc__main_menu.html' %}
    </div>

    <div class="details">
        {% include 'mainapp/includes/inc__category_menu.html' %}

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ hot_product.image }}" alt="">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="/media/{{ hot_product.image }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add_product' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>{{ hot_product.description }}</p>
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in same_products %}
                    <div class="block">
                        <a href="{% url 'mainapp:product_page' product.pk %}">
                            <img src="{{ product.image.url }}" alt="">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h4>{{ product.name }}</h4>
                                <p> {{ product.short_desc }} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}